### ISSUE TITLE
Content appended to wrong object

### ISSUE THREAD

**Issue by twisty-doerofthings** [adamjimenez/ui.tabs.overflowResize#1]
Line 115 uses `.appendTo( this.element.children(':last-child')` when adding the new `content` to the last `div`. In the Demo, this is `#tabs-3` and not `.tabpanel`. I suspect `.after( this.element.children(':last-child')` would generate the desired affect.

**Comment by adamjimenez** [comment]
insertAfter would have done it. But the original idea was to have the panels inside a container div for easier access.

**Comment by twisty-doerofthings** [comment]
That doesn't make sense. When you add the panel, it is created inside another panel, and hidden. So when you click on the tab for that specific panel, and the content is shown, it cannot be seen because it's within another panel that is hidden.

**Comment by adamjimenez** [comment]
the main panel is not hidden it is just a containing div, the demo works for me.

**Comment by twisty-doerofthings** [comment]
When you click on the `li.addTab`, a new `div` is created and appended after `/html/body/div[1]/div[3]`. That is working. I am specifically referring to the `add` feature, for example: `$(".tabpanel").tabs("add", "Test", "This is Test Text.");` The new `div` is created like so `/html/body/div[1]/div[3]/div` when you want it to be `/html/body/div[1]/div[4]`. You can see this here: https://jsfiddle.net/Twisty/ryhzwkph/9/

**Comment by adamjimenez** [comment]
You need to wrap your panels in a div like the demo:
https://github.com/adamjimenez/ui.tabs.overflowResize/commit/e5558a9dde3bc2e8baeff76788e1db099c503eac

**Comment by twisty-doerofthings** [comment]
Could you please site in the documentation where this instruction is given? This also deviates from Jquery UI format of `<div><ul><li><a></a></li></ul><div></div></div>`

**Comment by adamjimenez** [comment]
Docs are sparse but this is in the updated demo. This differs from the jQuery UI demo, but I don't believe it breaches any of their guidelines (correct me if I'm wrong). This could be added as an option, PR welcome.

**Comment by twisty-doerofthings** [comment]
I agree, I do not think it breaches any guidelines. Yet if someone has created code from the JQuery UI Tabs examples, and then adds your Plug-In, it will not work as expected without that additional `div`. I might take you up on your offer.
