### ISSUE TITLE
Put icon in tab title

### ISSUE THREAD

**Issue by jjp91** [adamjimenez/ui.tabs.overflowResize#3]
Hi,

Could it be possible to put icon/s alone/with text tab title.

Thanks

**Comment by adamjimenez** [comment]
I've updated the chrome demo to include tab icons.

**Comment by jjp91** [comment]
Thank you,

If you allow me, this kind of icons (ui-icon) are very small and when you click on it, tab selection change does not work.
But the very big deal for me, is the size of the icons. Even the close icon is bigger than the tab title icon.

I'd like to say that, i have search a lot of tabs systems out there, and this one is really at the same time nice and simple.

Realy thank you for the effort.

**Comment by adamjimenez** [comment]
The first one should be easy to fix by delegating the click event. The second can be tweaked with CSS. PRs welcome.

Edit: I've fixed the icon click to focus the tab.
